#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// 语音模块采样率：24kHz（输入输出）
#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 语音模块使用共享I2S时钟模式（麦克风和功放共享GPIO5/6）
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

// 麦克风 INMP441
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_4   // MIC_SD
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_5   // I2S_WS (共享)
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_6   // I2S_BCLK (共享)

// 功放 MAX98357A
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7   // SPK_DOUT
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_5   // I2S_WS (共享)
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_6   // I2S_BCLK (共享)

#else

#define AUDIO_I2S_GPIO_WS   GPIO_NUM_5
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_6
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_4
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7

#endif


// 按钮与LED
#define BUILTIN_LED_GPIO        GPIO_NUM_48  // 内置LED状态指示
#define BOOT_BUTTON_GPIO        GPIO_NUM_0   // BOOT按钮（启动/对话切换）
#define TOUCH_BUTTON_GPIO       GPIO_NUM_1   // TOUCH按钮（按住说话）
#define USER_BUTTON_1_GPIO      GPIO_NUM_46  // 用户按钮1（预留）
#define USER_BUTTON_2_GPIO      GPIO_NUM_47  // 用户按钮2（预留）
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC


// LCD显示屏 ILI9341 (SPI3总线)
#define OLED_DISPLAY_SDA_PIN GPIO_NUM_41
#define OLED_DISPLAY_SCL_PIN GPIO_NUM_42
#define OLED_DISPLAY_WIDTH   128
#define OLED_DISPLAY_HEIGHT  32
#define OLED_DISPLAY_MIRROR_X true
#define OLED_DISPLAY_MIRROR_Y true

#define DISPLAY_MOSI_PIN      GPIO_NUM_40  // LCD_MOSI (SDI)
#define DISPLAY_CLK_PIN       GPIO_NUM_41  // LCD_SCK
#define DISPLAY_DC_PIN        GPIO_NUM_39  // LCD_DC (数据/命令选择)
#define DISPLAY_RST_PIN       GPIO_NUM_NC  // LCD_RST (接3.3V或悬空)
#define DISPLAY_CS_PIN        GPIO_NUM_NC  // LCD_CS (接GND常使能)
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC  // LCD disabled; GPIO42 is used by OLED SCL


#ifdef CONFIG_LCD_ST7789_240X320
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ST7789_240X320_NO_IPS
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    false
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ST7789_170X320
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   170
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  35
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ST7789_172X320
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   172
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  34
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ST7789_240X280
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  280
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  20
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ST7789_240X240
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ST7789_240X240_7PIN
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 3
#endif

#ifdef CONFIG_LCD_ST7789_240X135
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  135
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  40
#define DISPLAY_OFFSET_Y  53
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ST7735_128X160
#define LCD_TYPE_ST7735_SERIAL
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  160
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  2
#define DISPLAY_OFFSET_Y  1
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ST7735_128X128
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  128
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR  false
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  32
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ST7796_320X480
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  480
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ST7796_320X480_NO_IPS
#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  480
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    false
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ILI9341_240X320
#define LCD_TYPE_ILI9341_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true  // 低电平点亮
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_ILI9341_240X320_NO_IPS
#define LCD_TYPE_ILI9341_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    false
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_GC9A01_240X240
#define LCD_TYPE_GC9A01_SERIAL
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif

#ifdef CONFIG_LCD_CUSTOM
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0
#endif


// 触摸屏 XPT2046 (SPI接口 + 中断)
#define TOUCH_SPI_CLK_PIN  GPIO_NUM_19  // T_CLK
#define TOUCH_SPI_CS_PIN   GPIO_NUM_20  // T_CS
#define TOUCH_SPI_MOSI_PIN GPIO_NUM_21  // T_DIN
#define TOUCH_SPI_MISO_PIN GPIO_NUM_16  // T_DO (与UART_RX时分复用)
#define TOUCH_IRQ_PIN      GPIO_NUM_18  // T_IRQ (触摸中断，低电平有效)

// STM32通信接口 (UART)
#define STM32_UART_TX_PIN  GPIO_NUM_17  // 发送到STM32 PA10
#define STM32_UART_RX_PIN  GPIO_NUM_16  // 接收STM32 PA9 (与T_DO时分复用)
#define STM32_UART_BAUD    115200

// UWB定位模块 DW1000 (独立SPI总线)
#define UWB_SPI_MOSI_PIN   GPIO_NUM_11  // UWB_MOSI
#define UWB_SPI_MISO_PIN   GPIO_NUM_13  // UWB_MISO
#define UWB_SPI_SCK_PIN    GPIO_NUM_12  // UWB_SCK
#define UWB_SPI_CS_PIN     GPIO_NUM_10  // UWB_CS
#define UWB_IRQ_PIN        GPIO_NUM_9   // UWB_IRQ (数据就绪中断)
#define UWB_RST_PIN        GPIO_NUM_14  // UWB_RST (硬件复位)

// RFID读卡器 RC522 (独立SPI总线)
    #define RFID_SPI_MOSI_PIN  GPIO_NUM_35  // RFID_MOSI
#define RFID_SPI_MISO_PIN  GPIO_NUM_37  // RFID_MISO
#define RFID_SPI_SCK_PIN   GPIO_NUM_36  // RFID_SCK
#define RFID_SPI_CS_PIN    GPIO_NUM_38  // RFID_CS

// MCP扩展功能引脚（可选）
#define MCP_LED_PIN        GPIO_NUM_2   // 可编程LED
#define MCP_LAMP_PIN       GPIO_NUM_3   // 灯光控制
#define MCP_ROOM_TX_PIN    GPIO_NUM_15  // 房间控制TX
#define MCP_ROOM_RX_PIN    GPIO_NUM_8   // 房间控制RX

// Human presence sensor, active high by default
#define HUMAN_SENSOR_GPIO        GPIO_NUM_33
#define HUMAN_SENSOR_ACTIVE_LEVEL 1

// A MCP Test: Control a lamp (保持兼容性)
#define SMOKE_SENSOR_1_GPIO        GPIO_NUM_39
#define SMOKE_SENSOR_2_GPIO        GPIO_NUM_40
#define SMOKE_SENSOR_ACTIVE_LEVEL  1
#define BUZZER_GPIO                GPIO_NUM_21
#define BUZZER_ACTIVE_LEVEL        0

#define STORAGE_LID_SERVO_GPIO        GPIO_NUM_18
#define STORAGE_LID_SERVO_OPEN_DEG    90
#define STORAGE_LID_SERVO_CLOSE_DEG   0
#define STORAGE_LID_AUTO_CLOSE_MS     10000

#define LAMP_GPIO GPIO_NUM_3

#endif // _BOARD_CONFIG_H_
